//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriesHandler.Database.Connector
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalError
    {
        public int id { get; set; }
        public string error_name { get; set; }
        public System.DateTime error_time { get; set; }
        public string message { get; set; }
        public string stack_trace { get; set; }
        public string context { get; set; }
        public string inner_message { get; set; }
    }
}
